apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: quote-deployment
  namespace: development
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: quote-service
    spec:
      containers:
        - name: quote-container
          image: datawire/quote:0.5.0
          ports:
            - containerPort: 8080
